version: '3'
services:
  db:
    image: postgres
    volumes:
      - Academy:/var/lib/postgresql/data

  web:
    build: .
    env_file:
      - jwt.env
      - database_info.env
    ports:
      - "4000:3000"
    depends_on:
      - db
      - sidekiq
      - redis
      - nginx
    volumes:
       - .:/espertofit_academy

  redis:
    image: redis
    volumes:
      - Redis_db:/var/lib/redis
    ports:
      - "6379:6379"
  
  sidekiq:  
    build: .
    volumes:
      - .:/espertofit_academy
    command: bundle exec sidekiq
    links:
      - db
    depends_on:
      - redis

  nginx:
    image: nginx
    build:
      context: .
      dockerfile: Dockerfile_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx/nginx.conf
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    command: /bin/bash -c " exec nginx -g 'daemon off;'"

volumes:
  Academy:
  Redis_db:

networks:
  default:
    external:
      name: EspertoFitNetwork