version: '3'
services:
  db:
    image: postgres
    volumes:
      - Academy:/var/lib/postgresql/data

  web:
    build: .
    env_file:
      - jwt.env
      - database_info.env
    ports:
      - "80:80"
    depends_on:
      - db
      - sidekiq
      - redis
    volumes:
       - .:/espertofit_academy

  redis:
    image: redis
    volumes:
      - Redis_db:/var/lib/redis
    ports:
      - "6379:6379"
  
  sidekiq:  
    build: .
    volumes:
      - .:/espertofit_academy
    command: bundle exec sidekiq
    links:
      - db
    depends_on:
      - redis



volumes:
  Academy:
  Redis_db:

networks:
  default:
    external:
      name: EspertoFitNetwork