version: '3'
services:
  db:
    image: postgres
    volumes:
      - Academy:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - db
    volumes:
       - .:/espertofit_academy

volumes:
  Academy:

networks:
  default:
    external:
      name: EspertoFitNetwork