FROM nginx
RUN apt-get update -qq && apt-get -y install apache2-utils
ENV RAILS_ROOT /espertofit_academy
WORKDIR $RAILS_ROOT
RUN mkdir log
COPY public public/
COPY nginx/nginx.conf /etc/nginx/conf.d/
RUN envsubst '$RAILS_ROOT' < /etc/nginx/conf.d/nginx.conf > /etc/nginx/conf.d/default.conf
CMD [ "nginx", "-g", "daemon off;" ]