development:
  base_url: http://esperto_fit_personal_web_run_1:3000
  payment_url: http://esperto_fit_payments_web_run_1:3000
production:
  base_url: http://0.0.0.0:5000
test:
  base_url: http://0.0.0.0:5000
  payment_url: http://esperto_fit_payments_web_run_1:3000