default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: espertofit_academy_dev


test:
  <<: *default
  database: espertofit_academy_test

